name: CI

on:
  pull_request:
    branches: ['unstable']

jobs:
  nixos-distro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
      with:
        install_options: --no-daemon
    - name: Test desktop build
      working-directory: ./tests
      run: nix eval '.#nixosConfigurations."desktop".config.system.build.toplevel'
    - name: Test laptop build
      working-directory: ./tests
      run: nix eval '.#nixosConfigurations."laptop".config.system.build.toplevel'
    - name: Test ARM build
      working-directory: ./tests
      run: nix eval '.#nixosConfigurations."arm".config.system.build.toplevel'
